// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/afs/cern.ch/user/s/sgottlie/CMSSW_13_1_0/src/BDT4/./analyzer_Data_131_triplets.C";

#endif
